
TRUNCATE TABLE `DOMAIN_CLASS`;
TRUNCATE TABLE `DOMAIN_MODEL`;
TRUNCATE TABLE `GRID_SERVICE`;
TRUNCATE TABLE `GRID_SERVICE_POCS`;
TRUNCATE TABLE `HOSTING_CENTER`;
TRUNCATE TABLE `HOSTING_CENTER_POCS`;
TRUNCATE TABLE `POINT_OF_CONTACT`;
TRUNCATE TABLE `STATUS_CHANGE`;
