
TRUNCATE TABLE SIMPLE_NAMES;

INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("CaDSR*","caDSR");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("EVS*","Enterprise Vocabulary Service");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("*CaArray*","caArray");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("*CaTissue*","caTissue");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("ChromosomalSegmentOverlapAcrossSources","CSOAS");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("OpenClinicaCRF","OpenClinical CRF");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("WorkflowFactoryService","Workflow Factory");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("TavernaWorkflowService","Taverna");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("AuthenticationService","Authentication");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("GlobalModelExchange","GME");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("GridGrouper","Grid Grouper");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("CredentialDelegationService","Credential Delegation");
INSERT INTO SIMPLE_NAMES (NAME,SIMPLE_NAME) VALUES ("FederatedQueryProcessor","Federated Query Processor ");

