
TRUNCATE TABLE SIMPLE_NAME;

INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("CaDSR*","caDSR");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("EVS*","Enterprise Vocabulary Service");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("*CaArray*","caArray");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("CaTissue_Core*","caTissue Core");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("CaTissue_Suite*","caTissue Suite");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("*CaTissueCore*","caTissue Core");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("*CaTissueSuite*","caTissue Suite");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("NCIA*","NCIA");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("caTissue*","caTissue");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("ChromosomalSegmentOverlapAcrossSources","CSOAS");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("OpenClinicaCRF","OpenClinical CRF");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("WorkflowFactoryService","Workflow Factory");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("TavernaWorkflowService","Taverna");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("AuthenticationService","Authentication");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("GlobalModelExchange","GME");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("GridGrouper","Grid Grouper");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("CredentialDelegationService","Credential Delegation");
INSERT INTO SIMPLE_NAME (PATTERN,SIMPLE_NAME) VALUES ("FederatedQueryProcessor","Federated Query Processor ");

